# Generated by Django 3.2.6 on 2022-07-04 11:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceId', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.UUID('c4f04a04-93aa-487b-9e2e-6e3d64eb11ad'))),
                ('dateActivated', models.DateField()),
                ('activated', models.BooleanField(default=False)),
                ('numberOfUsers', models.IntegerField(default=0)),
                ('maxUsers', models.IntegerField(default=0)),
                ('activatedTo', models.DateField(blank=True, null=True)),
                ('planTypes', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GROUP', 'Group'), ('COMPANY', 'Company')], default='Individual', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('companyName', models.CharField(max_length=100)),
                ('contactPhone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('licenseActivated', models.BooleanField()),
                ('superUser', models.BooleanField(default=False)),
                ('devices', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='license_api.devicedetails')),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='license_api.licensekey')),
            ],
        ),
    ]
