# Generated by Django 3.2.6 on 2022-07-08 13:34

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.UUID('ccc0a2ea-cc12-47bb-bd94-26b0929fb0d3'))),
                ('dateActivated', models.DateField()),
                ('activated', models.BooleanField(default=False)),
                ('numberOfUsers', models.PositiveIntegerField(default=0)),
                ('maxUsers', models.PositiveIntegerField(default=0)),
                ('activatedTo', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceID', models.CharField(blank=True, max_length=100, null=True)),
                ('licenseKey', models.CharField(blank=True, max_length=100, null=True)),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('companyName', models.CharField(max_length=100)),
                ('contactPhone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('licenseActivated', models.BooleanField(default=False)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='NATIONAL', max_length=128, region=None)),
                ('superUser', models.BooleanField(default=False)),
                ('deviceId', models.CharField(blank=True, max_length=100, null=True)),
                ('firstUse', models.BooleanField(default=True)),
                ('userNumbers', models.PositiveIntegerField(default=1)),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='license_api.licensekey')),
                ('subUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_sub', to='license_api.subuser')),
            ],
        ),
    ]
