# Generated by Django 3.2.6 on 2022-07-05 06:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('license_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.UUIDField(default=uuid.UUID('6d80c6b6-3f6e-4d80-b428-fbf3a4e17fd9')),
        ),
    ]
