# Generated by Django 3.2.6 on 2022-07-08 13:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('license_api', '0002_auto_20220708_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.UUIDField(default=uuid.UUID('23e5ce67-8376-4113-87e5-46838d5175b7')),
        ),
    ]
