# Generated by Django 3.2.6 on 2022-07-05 09:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('license_api', '0002_alter_licensekey_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(blank=True, choices=[('SUPER', 'Super'), ('ORDINARY', 'Ordinary')], max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.UUIDField(default=uuid.UUID('f4062227-5c1b-4786-9c22-40d6afc7504f')),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='userTypes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='license_api.usertype'),
        ),
    ]
