# Generated by Django 3.2.6 on 2022-07-05 12:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('license_api', '0003_auto_20220705_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceID', models.CharField(blank=True, max_length=100, null=True)),
                ('licenseKey', models.CharField(blank=True, max_length=100, null=True)),
                ('superUser', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='userTypes',
        ),
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.UUIDField(default=uuid.UUID('5ec35d31-508e-425f-9080-3606860fde7d')),
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='subUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='license_api.subuser'),
        ),
    ]
