# Generated by Django 3.2.6 on 2022-07-06 06:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('license_api', '0004_auto_20220705_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subuser',
            old_name='superUser',
            new_name='isActive',
        ),
        migrations.RemoveField(
            model_name='licensekey',
            name='planTypes',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='devices',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='deviceId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='planTypes',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GROUP', 'Group'), ('COMPANY', 'Company')], default='Individual', max_length=50),
        ),
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.UUIDField(default=uuid.UUID('49bf0775-afe8-4a3d-bac2-704329c3091a')),
        ),
        migrations.DeleteModel(
            name='DeviceDetails',
        ),
    ]
