# Generated by Django 3.2.6 on 2022-07-09 10:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('license_api', '0004_auto_20220708_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appVersion', models.CharField(blank=True, max_length=50, null=True)),
                ('appFile', models.FileField(upload_to='app')),
            ],
        ),
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.UUIDField(default=uuid.UUID('8c6253e0-6ad4-47a0-ae71-b02b6eb8480a')),
        ),
    ]
