# Generated by Django 3.2.6 on 2022-07-06 07:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('license_api', '0005_auto_20220706_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.UUIDField(default=uuid.UUID('dff51a6f-a8e4-471f-a0f5-48ad640427c8')),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='subUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_sub', to='license_api.subuser'),
        ),
    ]
