# Generated by Django 3.2.6 on 2022-07-18 06:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('license_api', '0005_auto_20220709_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.UUIDField(default=uuid.UUID('097a9ba1-365f-4f61-8a3e-7fd242055d2d')),
        ),
    ]
