# Generated by Django 3.2.6 on 2022-07-20 12:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('license_api', '0006_alter_licensekey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.UUIDField(default=uuid.UUID('a2fa61fd-e8ff-4311-a097-1f2c1295aed9')),
        ),
    ]
