# Generated by Django 3.2.6 on 2022-07-06 10:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('license_api', '0006_auto_20220706_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='numberOfUsers',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.UUIDField(default=uuid.UUID('7f91a6df-484a-4f5b-9092-eb8c8f764b0a')),
        ),
    ]
