# Generated by Django 3.2.6 on 2022-07-20 13:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('license_api', '0007_alter_licensekey_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatefile',
            name='uploadedDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.UUIDField(default=uuid.UUID('da66a9bc-2a0b-415d-8935-761bdc08ef3e')),
        ),
    ]
