# Generated by Django 3.2.6 on 2022-07-06 10:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('license_api', '0007_auto_20220706_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.UUIDField(default=uuid.UUID('4b7959f1-3855-49fd-8e77-a34a484e4a6d')),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='numberOfUsers',
            field=models.IntegerField(default=1),
        ),
    ]
