# Generated by Django 3.2.6 on 2022-07-06 10:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('license_api', '0008_auto_20220706_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='numberOfUsers',
            new_name='userNumbers',
        ),
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.UUIDField(default=uuid.UUID('e68c3db7-79e7-489e-9024-08a47dc2400d')),
        ),
    ]
