# Generated by Django 3.2.6 on 2022-07-21 07:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('license_api', '0008_auto_20220720_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.UUIDField(default=uuid.UUID('590791fa-2e9f-4d3d-8395-88fe150e232e')),
        ),
    ]
