# Generated by Django 3.2.6 on 2022-07-06 10:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('license_api', '0009_auto_20220706_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.UUIDField(default=uuid.UUID('a73d4f9e-2bc5-4bfd-b573-11d4df037d33')),
        ),
    ]
