# Generated by Django 3.2.6 on 2022-07-23 08:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('license_api', '0009_alter_licensekey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.UUIDField(default=uuid.UUID('875b0474-ef61-4ffa-afc9-58f89a863942')),
        ),
    ]
