# Generated by Django 3.2.6 on 2022-07-06 10:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('license_api', '0010_alter_licensekey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.UUIDField(default=uuid.UUID('38ecea7c-4db8-45dc-a196-3f2616a421ca')),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='userNumbers',
            field=models.IntegerField(),
        ),
    ]
