# Generated by Django 3.2.6 on 2022-07-06 10:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('license_api', '0011_auto_20220706_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.UUIDField(default=uuid.UUID('7ae93d83-058b-442f-bfb8-370d29c6952d')),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='userNumbers',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
