# Generated by Django 3.2.6 on 2022-07-06 10:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('license_api', '0012_auto_20220706_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.UUIDField(default=uuid.UUID('70a97a99-f3bd-42f3-a28f-8b172b8f3a6b')),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='licenseActivated',
            field=models.BooleanField(default=False),
        ),
    ]
