# Generated by Django 3.2.6 on 2022-07-06 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('license_api', '0013_auto_20220706_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.UUIDField(default=uuid.UUID('5f641a20-3cd7-4039-b9b8-284cf04f390f')),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='userNumbers',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
