# Generated by Django 3.2.6 on 2022-07-06 13:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('license_api', '0014_auto_20220706_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.UUIDField(default=uuid.UUID('2e6df874-0658-4bd3-a6d4-7cabbe863d1f')),
        ),
    ]
